api/urls.py
from django.urls import path, re_path

from api.views import LibroDetalleView, LibroListaView, LibroListaCustomView, LibroDetalleCustomView, TokenObtainView
from rest_framework_simplejwt.views import TokenObtainPairView

urlpatterns = [
    path('tokenDefault/', TokenObtainPairView.as_view(), name='token_pair'),
    path('tokenCustom/', TokenObtainView.as_view(), name='token_pair_custom'),
    path('test', LibroListaView.as_view(), name='libros_lista'),
    path('test/<int:pk>', LibroDetalleView.as_view(), name='libros_detalle'),   
    path('', LibroListaCustomView.as_view(), name='libros_lista_custom'),   
    path('<int:pk>', LibroDetalleCustomView.as_view(), name='libros_detalle_custom'),   
] 

primer_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_postalcodes_mexico import urls as django_postalcodes_mexico_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ventas.urls')),
    path('libros/', include('api.urls')),
    path('cp-', include(django_postalcodes_mexico_urls)),
]  

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

ventas/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LogoutView

from . import views


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login', views.LoginCustomView.as_view(), name='login'),
    path('logout', views.logoutCustom, name='logout'),
    path('servidor', views.ServidorViews.as_view(), name='servidor'),
    path('productos', views.ProductosView.as_view(), name='productos'),
    path('solicitud', views.solicitud, name='solicitud'),
    path('perfil', views.perfil_view, name='perfil'),
    path('ajaxEditarProductos', views.editar_productos, name='ajaxEditarProductos'),
    path('ajaxEliminarProductos', views.eliminar_producto, name='ajaxEliminarProductos'),
    path('ajaxFiltro', views.filtro_productos, name='ajaxFiltro'),
    path('ajaxFiltarEstados', views.filtrar_estados, name='ajaxFiltarEstados'),
    path('graficas', views.graficas, name='graficas'),

]

ventas/models.py
from django.db import models
from django.contrib.auth.models import User

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=500)
    precio = models.DecimalField(null=True, blank=True, max_digits=40, decimal_places=2)
    fecha_alta = models.DateTimeField(auto_now=True)
    archivos = models.FileField(upload_to='archivos/', max_length=300, default='archivos/terminos_y_Condiciones_registro.pdf')
    activo = models.BooleanField(default=True)

    
    def __str__(self):
        return str(self.nombre)



class cat_Estado(models.Model):	
	entidad_federativa = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now=True)
	updated_at = models.DateTimeField(auto_now=True)
	default = models.IntegerField(default=0)
	orden = models.IntegerField(default=1)
	codigo = models.CharField(max_length=45, blank=True)
	estatus = models.BooleanField(default=True)
		
	def __str__(self):
		return str(self.entidad_federativa)

class cat_Municipio(models.Model):

		clave = models.CharField(max_length=100)
		valor = models.CharField(max_length=250)
		cat_entidades_federativas = models.ForeignKey(cat_Estado, on_delete=models.CASCADE, related_name='fk_Municipio_Estado',default=1)
		created_at = models.DateTimeField(auto_now=True)
		updated_at = models.DateTimeField(auto_now=True)
		estatus = models.BooleanField(default=True)
		
		def __str__(self):
				return str(self.valor)

class Personas(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    edad = models.IntegerField()
    calle = models.CharField(max_length=100)
    colonia = models.CharField(max_length=100)
    codigo_postal = models.CharField(max_length=5)
    estado = models.ForeignKey(cat_Estado, on_delete=models.CASCADE)
    municipio = models.ForeignKey(cat_Municipio, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        return str(self.nombre)

class Solicitudes(models.Model):
    descripcion = models.CharField(max_length=600)
    request_id = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    lat = models.IntegerField()
    long = models.IntegerField()
    requested_datetime = models.DateTimeField()
    status = models.CharField(max_length=10)
    media_url = models.CharField(max_length=500, null=True, blank=True)
    agency_responsible = models.CharField(max_length=100, null=True, blank=True)
    activo = models.BooleanField(default=True)
    
    def __str__(self):
        return str(self.request_id)

ventas/forms.py
from dataclasses import field
from socket import fromshare
from django import forms
from ventas.models import Producto, Personas
'''
class ProductoForm(forms.Form):
    nombre = forms.CharField(label="Nombre del producto", widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa nombre del producto"}))
    descripcion = forms.CharField(label="Descripción detallada", widget=forms.Textarea(attrs={"class":"form-control","placeholder":"Ingresa la descripción"}))
    precio = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control","placeholder":"Ingresa el precio"}))
'''
class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ["nombre","descripcion","precio","archivos","activo"]
        widgets = {
            "nombre":forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa nombre del producto"}),
            "descripcion":forms.Textarea(attrs={"class":"form-control","placeholder":"Ingresa la descripción"}),
            "precio":forms.NumberInput(attrs={"class":"form-control","placeholder":"Ingresa el precio"}),
            "archivos":forms.FileInput(attrs={"class":"form-control"}),
            "activo":forms.CheckboxInput(),
        }

class FiltroProductoForm(forms.Form):
    nombre_filtro = forms.CharField(label="Nombre del producto", widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa nombre del producto"}))
    precio_min = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control","placeholder":"Ingresa el precio mínimo"}))
    precio_max = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control","placeholder":"Ingresa el precio máximo"}))
    activo_filtro = forms.IntegerField(widget=forms.CheckboxInput())

class LoginForm(forms.Form):
    usuario = forms.CharField(label="Usuario", widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa su usuario"}))
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Ingresa su contraseña"}))
     
class PersonasForm(forms.ModelForm):
    class Meta:
        model = Personas
        fields = ["usuario","nombre","apellidos","edad","calle","colonia","codigo_postal","estado","municipio"]
        widgets = {
            "usuario":forms.Select(attrs={'class': 'form-control'}),
            "nombre":forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa tu nombre"}),
            "apellidos":forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa tus apellidos"}),
            "edad":forms.NumberInput(attrs={"class":"form-control","placeholder":"Ingresa tu edad"}),
            "calle":forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa calle"}),
            "colonia":forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa colonia"}),
            "codigo_postal":forms.TextInput(attrs={"class":"form-control","placeholder":"Ingresa codigo postal"}),
            "estado":forms.Select(attrs={'class': 'form-control'}),
            "municipio":forms.Select(attrs={'class': 'form-control'}),
        }

templates/ventas/graficas.html
{% extends 'layouts/base.html' %}

{% block title %} Inicio {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block style %}

{% endblock style %}
{% block content %}

<div class="container">

    <div class="header pb-6 mt-4">
      <div class="container-fluid">
        <div class="header-body">
      <div class="row">
        <div class="col-xl-12">
          <div class="card">
            <div class="card-header border-0">
              <div class="row align-items-center">
                <div class="col-12">
                  <h1 class="mb-0 color-primario">Graficas con Chart.js</h1>
                </div>
                <div class="col-12">
                  <canvas id="myChart"></canvas>
                </div>
                <div class="col-12">
                    <canvas id="reportes_mensuales"></canvas>
                </div>

              </div>
            </div>
        
          </div>
        </div>
      </div>
      </div>
      </div>

</div>
    

    </div>

</div>

{% endblock content %}


{% block scripts %}

<script type='text/javascript'>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['Rojo', 'Azul', 'Amarillo', 'Verde', 'Morado', 'Naranja'],
      datasets: [{
        label: 'Numero de votos',
        data: [12, 19, 3, 5, 2, 3],
        borderWidth: 1
      }]
    },
    options: {
      indexAxis: 'x',
      scales: {
          y: {
            display: true,
            title: {
                display: true,
                text: "Cantidad de votos"
            }
          },
        x: {
            display: true,
            title: {
                display: true,
                text: "Colores"
            },
          beginAtZero: true
        }
      }
    }
  });
  meses = "{{meses}}"
  var meses_array = JSON.parse(meses)
  console.log(meses_array)
  var data = {
      labels: ['Enero','Febrero','Marzo','Abril','Mayo','Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre'],
      datasets: [{
        label: 'Numero de reportes',
        data: meses_array,
        borderWidth: 2,
        borderColor: "black",
        backgroundColor: ['rgba(0, 128, 0, .3)',"yellow","blue","red","orage","pink","gray"],
        fill:true
      }]
    }
  var options = {
      scales: {
          y: {
            display: true,
            title: {
                display: true,
                text: "Cantidad de reportes"
            }
          },
        x: {
            display: true,
            title: {
                display: true,
                text: "Meses"
            },
          beginAtZero: true
        }
      }
    }

  var reportes_mensuales = new Chart('reportes_mensuales', {
    type: 'pie',
    data: data,
    options: options
  });


</script>
{% endblock scripts %}

templates/ventas/login.html
{% extends 'layouts/base.html' %}
{% load static %}

    {% block title %} Bienvenida {% endblock title %}

    {% block content %}
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
          
          <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form action="{% url 'login' %}" method="post">
                  {% csrf_token %}

              <div class="divider d-flex align-items-center my-4">
                <h2 class="text-center fw-bold mx-3 mb-0">Iniciar sesión</h2>
              </div>

              <!-- Email input -->
              <div class="form-outline mb-4">
                <label class="form-label" for="form3Example3">Usuario</label>

                  {{ loginForm.usuario }}
                
              </div>

              <!-- Password input -->
              <div class="form-outline mb-3">
                <label class="form-label" for="form3Example4">Contraseña</label>

                  {{ loginForm.password }}

              </div>
              <div class="col-12 text-right"><small class="text-danger">{{ error }}</small></div>

              <div class="d-flex justify-content-between align-items-center">
                <!-- Checkbox >
                <div class="form-check mb-0">
                  <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                  <label class="form-check-label" for="form2Example3">
                    Remember me
                  </label>
                </div-->
                <a href="#!" class="text-body">¿Olvidó su contraseña?</a>
              </div>

              <div class="text-center text-lg-start mt-4 pt-2">
                <button type="submit" class="btn btn-primary btn-lg bgcolor-secundario bordecolor-secundario"
                  style="padding-left: 2.5rem; padding-right: 2.5rem;">Entrar</button>
               
              </div>

            </form>
          </div>
        </div>
      </div>

    {% endblock content %}

templates/ventas/perfil.html
{% extends 'layouts/base.html' %}
{% load static %}

    {% block title %} Bienvenida {% endblock title %}

    {% block content %}
    <div class="container">
        <div class="row">
          
          <div class="col-12">
            <form>
              {{personasForm.as_p}}
            </form>
          
          </div>
        </div>
      </div>

    {% endblock content %}
    {% block scripts %}
    <script>
      $(document).ready(function(){
        $("#id_municipio").attr("disabled","disabled")
      });
      $("#id_estado").change(function(){
        id_estado = $(this).val()
        $.ajax({
        method: "POST",
        url: "{% url 'ajaxFiltarEstados' %}",
        headers: {
            'X-CSRFToken':'{{ csrf_token }}'
        },
        data: {
              "id_estado":id_estado
            },
        success: function(response){
            $("#id_municipio").removeAttr("disabled")
            opcion = ""
            $("#id_municipio").html("<option value=''>-----</opcion>")
            $.each( response["municipios"], function( key, value ){
                opcion += "<option value='"+value.id+"'>"+value.nombre+"</opcion>"
            });
            $("#id_municipio").append(opcion)
            
         
       
        }
      });
      });
    </script>
    {% endblock scripts %}

templates/ventas/productos.html
{% extends 'layouts/base.html' %}

{% block title %} Productos {% endblock title %}

{% block style %}
        
{% endblock style %}

{% block content %}
       
        <div class="container">
            <div class="row">
                <div class="col-12 mt-5">
                    <form>
                        <div class="row">
                            {% csrf_token %}
                            <div class="col-3 mb-3">
                                {{formProductosFiltro.nombre_filtro.label}}
                                {{formProductosFiltro.nombre_filtro}}
                            </div>
                            <div class="col-3 mb-3">
                                {{formProductosFiltro.precio_min.label}}
                                {{formProductosFiltro.precio_min}}
                            </div>
                            <div class="col-3 mb-3">
                                {{formProductosFiltro.precio_max.label}}
                                {{formProductosFiltro.precio_max}}
                            </div>
                            <div class="col-3 mb-3">
                                {{formProductosFiltro.activo_filtro.label}}
                                {{formProductosFiltro.activo_filtro}}
                            </div>
                            <div class="col-2">
                                <button id="filtrar_productos" type="button" onclick="" class="btn btn-primary">Filtrar</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-12 mt-5">
                    <table class="table" id="tabla">
                        <thead>
                            <tr>
                                <th>Nombre de Producto</th>
                                <th>Descripción</th>
                                <th>Precio</th>
                                <th>Archivo</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody id="productos_body">
                            {% if productos %}
                                {% for producto in productos %}
                                <tr id="{{producto.id}}_fila">
                                    <td id="{{producto.id}}_nombre">{{ producto.nombre }}</td>
                                    <td id="{{producto.id}}_descripcion">{{ producto.descripcion }}</td>
                                    <td id="{{producto.id}}_precio">{{ producto.precio }}</td>
                                    {% if producto.archivos %}
                                        <td id="{{producto.id}}_archivo"><a target="blank" href="{{ producto.archivos.url }}">{{ producto.archivos.name }}</a></td>
                                    {%else %}
                                        <td id="{{producto.id}}_archivo">Sin archivo</td>
                                    {% endif %}
                                    <td>
                                        <button class="btn btn-primary" onclick="editar({{producto.id}})"> Editar </button>
                                        <button class="btn btn-danger" onclick="eliminar({{producto.id}})"> Eliminar </button>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% else %}
                            <tr>
                                <th>NO HAY PRODUCTOS REGISTRADOS</th>
                            <tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <hr>
                <div class="col-12 mt-5">
                    <form action="{% url 'productos' %}" method="POST" id="producto_form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{formProductos.nombre.label}}
                            {{formProductos.nombre}}
                          </div>
                          <div class="mb-3">
                            {{formProductos.descripcion.label}}
                            {{formProductos.descripcion}}
                          </div>
                          <div class="mb-3">
                            {{formProductos.precio.label}}
                            {{formProductos.precio}}
                        </div>
                        <div class="mb-3">
                            {{formProductos.archivos.label}}
                            {{formProductos.archivos}}
                        </div>
                        <div class="mb-3">
                            {{formProductos.activo.label}}
                            {{formProductos.activo}}
                        </div>
                          <input type="hidden" id="id_formulario">
                          <button id="boton_guardar" type="button" onclick="guardarDato()" class="btn btn-primary">Guardar</button>
                          <button id="boton_actualizar" type="button" class="btn btn-primary" style="display: none;">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
        
    {% endblock content%}
{% block scripts %}
<script type="text/javascript">
    $(document).ready(function(){

   
    function eliminar(id){
        if(confirm('¿Está seguro de que quiere eliminar el producto? id: '+id)){
            $.ajax({
        method: "POST",
        url: "{% url 'ajaxEliminarProductos' %}",
        headers: {
            'X-CSRFToken':'{{ csrf_token }}'
        },
        data: {
              "id":id,
        },
        success: function(response){
            $("#"+response.id+"_fila").remove()
        }
      });
        }
        

    }
    function borarFormulario(){
        $("#id_nombre").val("")
        $("#id_descripcion").val("")
        $("#id_precio").val("")
    }
    function validarFormulario(){
        let error = false
        if($("#id_nombre").val()==""){
            $("#id_nombre").addClass("is-invalid")
            error = true
        }
        if($("#id_descripcion").val()==""){
            $("#id_descripcion").addClass("is-invalid")
            error = true
        }
        if($("#id_precio").val()==""){
            $("#id_precio").addClass("is-invalid")
            error = true
        }
        return error

    }
    let id = 1;

    function guardarDato(){
        
        let formHasError = validarFormulario()
        if(!formHasError){
            
            $("#producto_form").submit()
        }
    }
    function editar(id){
        clearError()
        $("#boton_actualizar").show()
        $("#boton_guardar").hide()
        let nombre = $("#"+id+"_nombre").text()
        let descripcion = $("#"+id+"_descripcion").text()
        let precio = $("#"+id+"_precio").text()
        $("#id_formulario").val(id)
        $("#id_nombre").val(nombre)
        $("#id_descripcion").val(descripcion)
        $("#id_precio").val(precio)

    }
    function clearError(){
        $("#id_nombre").removeClass("is-invalid")
        $("#id_descripcion").removeClass("is-invalid")
        $("#id_precio").removeClass("is-invalid")

    }
    $("#id_nombre").on('input',function(){
        $(this).removeClass("is-invalid")
    });
    $("#id_descripcion").on('input',function(){
        $(this).removeClass("is-invalid")
    });
    $("#id_precio").on('input',function(){
        $(this).removeClass("is-invalid")
    });

    $("#filtrar_productos").click(function(){
        var nombre = $('#id_nombre_filtro').val()
        var precio_min = $('#id_precio_min').val()
        var precio_max = $('#id_precio_max').val()
        var activo = $('#id_activo_filtro').is(":checked")

        $.ajax({
            method: "POST",
            url: "{% url 'ajaxFiltro' %}",
            headers: {
                'X-CSRFToken':'{{ csrf_token }}'
            },
            data: {
                "nombre":nombre,
                "precio_min":precio_min,
                "precio_max":precio_max,
                "activo":activo
                },
            success: function(response){
                productos = response["productos"];
                
                if(Object.keys(productos).length > 0){
                    $('#productos_body').html("")
                    tbody=""
                    $.each( productos, function( key, value ){
                        nombre_archivo = value.archivo_nombre != "" ? value.archivo_nombre : "Sin archivo"
                        url_archivo = value.archivo_url != "" ? value.archivo_url : "#"
                        tr = '<tr id="'+key+'_fila">'+
                                    '<td id="'+key+'_nombre">'+value.nombre+'</td>'+
                                    '<td id="'+key+'_descripcion">'+value.descripcion+'</td>'+
                                    '<td id="'+key+'_precio">'+value.precio+'</td>'+
                                        '<td id="'+key+'_archivo"><a target="blank" href="'+url_archivo+'">'+nombre_archivo+'</a></td>'+
                                    '<td>'+
                                        '<button class="btn btn-primary" onclick="editar('+key+')"> Editar </button>'+
                                        '<button class="btn btn-danger" onclick="eliminar('+key+'})"> Eliminar </button>'+
                                    '</td>'+
                                '</tr>'
                        tbody += tr

                    });
                    $('#productos_body').html(tbody)
                }
                else{
                    $('#productos_body').html(
                    '<tr><td></td><td></td><td><h3>No se encontraron resultados</h3></td>'+
                    '<td></td><td></td></tr>');
                }
            }
        });
    });

    $("#boton_actualizar").click(function(){
        
        let id = $("#id_formulario").val()
        let nombre = $("#id_nombre").val();
        let descripcion = $("#id_descripcion").val();
        let precio = $("#id_precio").val();
        let formHasError = validarFormulario()
        if(!formHasError){
     $.ajax({
        method: "POST",
        url: "{% url 'ajaxEditarProductos' %}",
        headers: {
            'X-CSRFToken':'{{ csrf_token }}'
        },
        data: {
              "id":id,
              "nombre":nombre,
              "descripcion":descripcion,
              "precio":precio
            },
        success: function(response){
            $("#"+response.id+"_nombre").text(response.nombre)
            $("#"+response.id+"_descripcion").text(response.descripcion)
            $("#"+response.id+"_precio").text(response.precio)
            $("#boton_actualizar").hide()
            $("#boton_guardar").show()
            borarFormulario()
         
       
        }
      });
            
        }
    });

    
    $("#agregar").click(function(){
        let fila = "<tr id='editable'><td>Daniel</td><td>Programador</td><td>78</td><tr>"
        $('#tabla').append(fila)
    });
    $("#editar").click(function(){
        let fila = "<td>Alejandro</td><td>Diseñador</td><td>21</td>"
        $('#editable').empty()
        $('#editable').append(fila)
        $('#editable').removeAttr("id")
    });
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

{% endblock scripts %}

templates/ventas/servidores.html
{% extends 'layouts/base.html' %}
{% load static %}

    {% block title %} Bienvenida {% endblock title %}

    {% block content %}
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
          
          <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
              <h1>Bienvenido Servidor </h1>
          </div>
        </div>
      </div>

    {% endblock content %}